name: mlflow-examples-keras_tf_mnist
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip:
    - mlflow
    #- tensorflow==2.5.0 # Fails: ONNX training on Mac and Debian
    #- tensorflow==2.4.1 # Fails: ONNX training on Mac and Debian
    - tensorflow==2.3.0  # OK:    ONNX training on Mac and Debian
    - onnx==1.9.0
    - onnxmltools==1.7.0
    - onnxruntime==1.7.0
    #- onnx==1.10.1  # Fails: AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
    #- onnxmltools==1.9.1
    #- onnxruntime==1.8.1
    - keras2onnx==1.7.0
    - Pillow
