name: mlflow-examples-sklearn-conda
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip:
    - mlflow>=2.4.2
    - scikit-learn
    - matplotlib
    - onnx==1.15.0
    - onnxruntime==1.16.3
    - skl2onnx==1.16.0
    - pyspark==3.3.1
    - shortuuid
