FROM continuumio/miniconda3

RUN apt-get update

RUN pip install mlflow==1.14.1
RUN pip install scikit-learn==0.20.2
RUN pip install matplotlib==3.2.1
RUN pip install pyarrow==0.17
RUN pip install onnx==1.8.0
RUN pip install onnxmltools==1.7.0
RUN pip install onnxruntime==1.7.0
